### ISSUE TITLE
בניית תריחשי שימוש

### ISSUE THREAD

**Issue by maimonin** [aviferdman/Workshop-on-Software-Engineering-Project#2]

**Comment by maimonin** [comment]
- [ ] 1.1
- [ ] 2.1
- [ ] 2.2
- [ ] 2.3
- [ ] 2.4
- [ ] 2.5
- [ ] 2.6
- [ ] 2.7
- [ ] 2.8
- [ ] 2.9
- [ ] 3.1
- [ ] 3.2
- [ ] 3.7
- [ ] 4.1
- [ ] 4.2
- [ ] 4.3
- [ ] 4.5
- [ ] 4.6
- [ ] 4.7
- [ ] 4.9
- [ ] 4.11
- [ ] 5.1
- [ ] 6.4
- [ ] 7
- [ ] 8

**Comment by maimonin** [comment]
- [ ] ךשךש

**Comment by maimonin** [comment]
להוסיף דיאגרמה למשימות

**Comment by boaz23** [comment]
לבטים ונקודות למחשבים לגבי תרחישי השימוש
 - [ ] האם בתרחיש שימוש 15, הזנת הצעה בלוטו, המשתמש מזין מחיר או סיכויי הצלחה?
 - [ ] shop owner - האם צריך pre-condition לזה שיהיה מחובר או שזה חלק מההגדרה של shop-owner?
 - [ ] האם ב-print הכוונה ל-print ל-terminal או בהקשר כללי של הצגה למסך?
 - [ ] האם כדאי לפצל עדכון של מדיניות וסוגים לתרחישי שימוש בודדים של מחיקה, שינוי של שדות והוספה? האם אפשר להגיד פשוט update? תקף גם לתרחיש שימוש של עדכון עגלת הקניות
 - [ ] כפל בתנאים ומדיע לגבי תרחישי שימוש: מנהל חנות צריך הרשאות כדי לבצע פעולות. לכן צריך אותו כ-actor בכל תרחיש שימוש של בעל חנות עם pre-condition מתאים.
איך אפשר לרשום זאת בלי כפילויות?
 - [ ] האם כדאי לבפצל את תרחיש שימוש 12, תגובה של מנהל/בעל חנות להצעת מחיר, לתרחישי שימוש של אישור, דחייה והצעת נגד?

**Comment by maimonin** [comment]
split edit cart to remove add and change quantity
change print to return
