### ISSUE TITLE
בניית תרשים מחלקות לבן

### ISSUE THREAD

**Issue by maimonin** [aviferdman/Workshop-on-Software-Engineering-Project#3]

**Comment by GilHatav** [comment]
Class Diagram Drawio xml Link: 
[https://drive.google.com/file/d/14pbjVomP8l7tBtWeBTKdq4Cs1AtB5BKF/view?usp=sharing](url)

**Comment by maimonin** [comment]
updated link :)
https://drive.google.com/file/d/1UU_OYvZ3zd-_uJ8EjmepWBMQiJHIOYFc/view?usp=sharing
