### ISSUE TITLE
בניית דיאגרמת ארכיטקטורה

### ISSUE THREAD

**Issue by maimonin** [aviferdman/Workshop-on-Software-Engineering-Project#4]

**Comment by aviferdman** [comment]
קישור לדיאגרמה:
https://drive.google.com/file/d/1b0PAvgWk67sDrSV6EiUz8-0T90tZG0RS/view?usp=sharing

**Comment by aviferdman** [comment]
קישור מעודכן לדיאגרמה:
https://app.diagrams.net/#G1b0PAvgWk67sDrSV6EiUz8-0T90tZG0RS
