### ISSUE TITLE
תכנון בדיקות לקוח

### ISSUE THREAD

**Issue by maimonin** [aviferdman/Workshop-on-Software-Engineering-Project#5]
https://docs.google.com/document/d/1yJxF8zLSXeW7wPrbuE8UbVoCshf9qii46FLWHTvf924/edit

**Comment by boaz23** [comment]
Task distribution:
Uses cases 5-8, 21-23, 24-29, Total: 13
Uses cases 9-20, Total: 12
Uses cases 4, 30-40, Total: 12

**Comment by boaz23** [comment]
Use cases distribution
Boaz: 4-8, communicate later when done on what will be left
Inbar: 9-20
Romi: 21-*

**Comment by maimonin** [comment]
Use cases distribution
Boaz: 4-11, communicate later when done on what will be left
Inbar: 11-22
Romi: 23-32
Gil: 33-end
